// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biopraphy: dynamic(() => import("./Biography")),
  hero: dynamic(() => import("./Hero")),
  techlist: dynamic(() => import("./Techlist")),
};
